const Joi = require('joi')
const Customer = require('../models/customer')
const EarthPosition = require('../models/earthPosition')

/**
 * @see: https://github.com/hapijs/joi/blob/master/API.md
 */
const schema = Joi.object().keys({
  latitude: Joi.number().required(),
  name: Joi.string().required(),
  user_id: Joi.number().integer().required(),
  longitude: Joi.number().required()
})

/**
 *
 * @param {string} line
 * @param {Customer} customer generated by the input line
 * @throws {Error} when line is malformed
 */
const parseLine = function (line) {
  const customerData = Joi.validate(line, schema)

  if (customerData.error !== null) {
    throw new Error(customerData.error.message)
  }

  const earthPosition = new EarthPosition(customerData.value.latitude, customerData.value.longitude)
  return new Customer(customerData.value.user_id, customerData.value.name, earthPosition)
}

/**
 * parse a file content to a customer list
 * @param {string} text
 * @param {Customer[]} text
 */
module.exports.parseText = function (text) {
  return text
    .split('\n')
    .filter(n => n)
    .map(line => parseLine(line))
}
